### ISSUE TITLE
Too many clusters generated when using default parameters

### ISSUE THREAD

**Issue by KshitijAggarwal** [realfastvla/rfpipe#41]
Running the scan with the default parameters of clustering is generating too many candidates, even if there was just one transient in the dataset (found when running pipeline on `16A-459_TEST_1hr_000.57633.66130137732.scan7.cut`), which implies that the clustering is not being done efficiently. Increasing the `min_cluster_size` while setting the state resolves the issue though.

**Comment by caseyjlaw** [comment]
I'll bump the `min_cluster_size` up by 1 to a value of 3. Hopefully that helps a bit.
